// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9GspwjR5_7FiPuC4Rl9ZZLmNi7rG-tTw',
    appId: '1:867301493020:web:a7e5f69e678668e07912d9',
    messagingSenderId: '867301493020',
    projectId: 'visiosphere-app',
    authDomain: 'visiosphere-app.firebaseapp.com',
    storageBucket: 'visiosphere-app.firebasestorage.app',
    measurementId: 'G-R67C1KTNBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyyaE5Jifq--0EPnyDd-WY05UlTtEKYU',
    appId: '1:867301493020:android:3515dac5d5ad272d7912d9',
    messagingSenderId: '867301493020',
    projectId: 'visiosphere-app',
    storageBucket: 'visiosphere-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL71WSobvIDwrQ-gCuXU0Y7GWhSPx3EZI',
    appId: '1:867301493020:ios:de246a74d493500d7912d9',
    messagingSenderId: '867301493020',
    projectId: 'visiosphere-app',
    storageBucket: 'visiosphere-app.firebasestorage.app',
    iosBundleId: 'com.example.visiosphereMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL71WSobvIDwrQ-gCuXU0Y7GWhSPx3EZI',
    appId: '1:867301493020:ios:de246a74d493500d7912d9',
    messagingSenderId: '867301493020',
    projectId: 'visiosphere-app',
    storageBucket: 'visiosphere-app.firebasestorage.app',
    iosBundleId: 'com.example.visiosphereMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9GspwjR5_7FiPuC4Rl9ZZLmNi7rG-tTw',
    appId: '1:867301493020:web:c8fd418855b788aa7912d9',
    messagingSenderId: '867301493020',
    projectId: 'visiosphere-app',
    authDomain: 'visiosphere-app.firebaseapp.com',
    storageBucket: 'visiosphere-app.firebasestorage.app',
    measurementId: 'G-FZ9RD8WMVJ',
  );
}
